# Generated by Django 5.0.3 on 2024-03-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='redes',
            field=models.ManyToManyField(to='service.redes', verbose_name='Redes Sociales'),
        ),
    ]
