# Generated by Django 5.0.3 on 2024-03-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_redes_service_redes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='redes',
            new_name='rede',
        ),
    ]
