# Generated by Django 5.0.3 on 2024-03-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_redes_rede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='rede',
            options={'ordering': ['-created'], 'verbose_name': 'Rede Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterField(
            model_name='rede',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
