# Generated by Django 5.0.3 on 2024-03-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_category_options_alter_rede_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='ubicacion',
            field=models.ManyToManyField(to='service.provincia', verbose_name='Provincias'),
        ),
    ]
