# Generated by Django 5.0.3 on 2024-03-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_provincia_service_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede',
            name='url',
        ),
        migrations.AlterField(
            model_name='service',
            name='redes',
            field=models.ManyToManyField(blank=True, null=True, to='service.rede', verbose_name='Redes Sociales'),
        ),
    ]
