# Generated by Django 5.0.3 on 2024-04-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_rede_url_alter_service_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categoria',
            field=models.ManyToManyField(related_name='get_service', to='service.category', verbose_name='categorias'),
        ),
    ]
