# Generated by Django 5.0.3 on 2024-04-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_service_image1_service_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='imagen1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='imagen2'),
        ),
    ]
