# Generated by Django 5.0.3 on 2024-04-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_image1_alter_service_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='redes',
        ),
        migrations.AddField(
            model_name='service',
            name='gps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='rede',
        ),
    ]
