# Generated by Django 5.0.3 on 2024-04-01 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_service_redes_service_gps_service_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en un formato válido.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
