# Generated by Django 5.0.3 on 2024-04-01 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en un formato válido.', regex='^[6-9]\\d{7}$')]),
        ),
    ]
