# Generated by Django 5.0.3 on 2024-04-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_service_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='whatsapp',
        ),
    ]
