# Generated by Django 5.0.3 on 2024-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_service_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=200, unique=True, verbose_name='nombre Clave')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['-created'],
            },
        ),
    ]
