# Generated by Django 5.0.3 on 2024-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
