# Generated by Django 5.0.3 on 2024-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_links_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
