# Generated by Django 5.0.3 on 2024-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='distrito',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Distrito'),
        ),
    ]
