# Generated by Django 5.0.3 on 2024-04-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_service_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name=range(1, 5)),
        ),
    ]
