# Generated by Django 5.0.3 on 2024-04-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image2',
        ),
    ]
