# Generated by Django 5.0.3 on 2024-04-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_slider_image1_remove_slider_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
