# Generated by Django 5.0.3 on 2024-04-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_service_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='gps',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
