# Generated by Django 5.0.3 on 2024-04-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_service_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
    ]
