# Generated by Django 5.0.3 on 2024-04-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre'),
        ),
    ]
