# Generated by Django 5.0.3 on 2024-04-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_alter_category_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='logo',
            new_name='path',
        ),
        migrations.AddField(
            model_name='category',
            name='path1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre'),
        ),
    ]
