# Generated by Django 4.0.6 on 2024-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_alter_category_path_alter_category_path1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Path1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='path1',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Path2'),
        ),
    ]
