# Generated by Django 3.2.25 on 2024-04-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_category_path_alter_category_path1'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
