# Generated by Django 3.2.25 on 2024-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_slider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='sonline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Slider_de_online',
                'verbose_name_plural': 'Sliders_de_online',
            },
        ),
    ]
