# Generated by Django 3.2.25 on 2024-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('texto', models.CharField(blank=True, max_length=200, null=True, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tablero_de_online',
            },
        ),
    ]
