# Generated by Django 3.2.25 on 2024-05-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_service_usuario_id'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='negocio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
